name: posha
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.5.0 <4.0.0"
dependencies:
  cached_network_image: ^3.4.1
  collection: ^1.19.1
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  get_it: ^9.2.0
  go_router: ^17.0.0
  google_fonts: ^6.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.6.0
  path_provider: ^2.1.5
  photo_view: ^0.15.0
  skeletonizer: ^2.1.2
  url_launcher: ^6.3.2
  youtube_player_flutter: ^9.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.5.4
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
